export default {
    FETCH_PAGES_REQUEST: "FETCH_PAGES_REQUEST",
    FETCH_PAGES_SUCCESS: "FETCH_PAGES_SUCCESS",
    FETCH_PAGES_FAIL: "FETCH_PAGES_FAIL",
    INITIAL_FETCH_ALL_REQUEST: "INITIAL_FETCH_ALL_REQUEST",
    INITIAL_FETCH_ALL_SUCCESS: "INITIAL_FETCH_ALL_SUCCESS",
    INITIAL_FETCH_ALL_FAIL: "INITIAL_FETCH_ALL_FAIL",
    FETCH_OPTIONS_REQUEST: "FETCH_OPTIONS_REQUEST",
    FETCH_OPTIONS_SUCCESS: "FETCH_OPTIONS_SUCCESS",
    FETCH_OPTIONS_FAIL: "FETCH_OPTIONS_FAIL",
    TOGGLE_MENU: "TOGGLE_MENU",
};
