export default {
    FETCH_PAGE_REQUEST: "FETCH_PAGE_REQUEST",
    FETCH_PAGE_SUCCESS: "FETCH_PAGE_SUCCESS",
    FETCH_PAGE_FAIL: "FETCH_PAGE_FAIL",
    INITIAL_FETCH_ALL_REQUEST: "INITIAL_FETCH_ALL_REQUEST",
    INITIAL_FETCH_ALL_SUCCESS: "INITIAL_FETCH_ALL_SUCCESS",
    INITIAL_FETCH_ALL_FAIL: "INITIAL_FETCH_ALL_FAIL",
    FETCH_OPTIONS_REQUEST: "FETCH_OPTIONS_REQUEST",
    FETCH_OPTIONS_SUCCESS: "FETCH_OPTIONS_SUCCESS",
    FETCH_OPTIONS_FAIL: "FETCH_OPTIONS_FAIL",
    TOGGLE_MENU: "TOGGLE_MENU",
    START_LOADING: "START_LOADING",
    STOP_LOADING: "STOP_LOADING",
};
