name: remote ssh command
on: [push]
jobs:

  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: sh sjdco-2020/rebuild.sh

  slackNotification:
    name: Slack Notification Demo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Slack Notification Demo
      uses: bryan-nice/slack-notification@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: 'Pushed SJDco Successfully'
        SLACK_MESSAGE: 'The repo ${{secrets.GITHUB_REPOSITORY}} was pushed successfully to ${{secrets.HOST}}'
